version: '3.1'

services:

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ./db:/var/lib/mysql
